In [69]:
%matplotlib notebook
import numpy as np ##importing modules
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
data=pd.read_table('data.txt',header=None,sep=",") ##reading the comma separated csv file
df=pd.DataFrame(data) ##pandas dataframe
print(df[6].unique())##labels
df[3]=df[3].replace('more',5)
df[2]=df[2].replace('5more',5)
y_lable=df[6]
del df[6]
#print(y_label)


['unacc' 'acc' 'vgood' 'good']
[2 2 2 ... 2 1 3]


In [72]:
df=pd.get_dummies(df,columns=[4],drop_first=True) ##one hot encoding the ordinal catagorical var
from sklearn import preprocessing
le = preprocessing.LabelEncoder() ##simple encoding of catagorical vars 
df[0]=le.fit_transform(df[0])
df[1]=le.fit_transform(df[1])
df[5]=le.fit_transform(df[5])

(1728, 7)


In [73]:
print(df.shape)

(1728, 7)


In [76]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
y_label=le.fit_transform(y_label)##encoding the labels
print(y_label)

[2 2 2 ... 2 1 3]


In [75]:
print(y_label)
X_train, X_test, y_train, y_test = train_test_split(df,y_label, random_state = 0,shuffle=False) ##splitting the data into training nad testing
print(y_test.shape)
from sklearn.svm import SVC  ##support vector machine for classification
clf = SVC(C=10,kernel='rbf').fit(X_train, y_train)
print(clf.score(X_train,y_train))
print(clf.score(X_test,y_test))


[2 2 2 ... 2 1 3]
(432,)
0.9976851851851852
0.8935185185185185


In [12]:
from sklearn.dummy import DummyClassifier ##cheking the imbalancing of the datset by creating a dummy classifier based on most frequent strategy
dummy=DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
print(dummy.score(X_test,y_test))
y_dummy_predictions = dummy.predict(X_test) ## the accuracy came around 60% while the SVC accuracy was 90% hence it is cleared that the model i mad is not imbalanced

0.5972222222222222
